name: Run Lua Reverse Tests
on: [push]
jobs:
  Run-Lua-Reverse-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Install stock luajit
        run: sudo apt-get install luajit
      - name: Test reverse find-dups
        run: cd reverse && luajit test-find-dups.lua
      - name: Test reverse json-filter
        run: cd reverse && luajit test-json-filter.lua
      - name: Test reverse next-json-token
        run: cd reverse && luajit test-next-json-token.lua
      - name: Test reverse parse-bytes
        run: cd reverse && luajit test-parse-bytes.lua
      - name: Test reverse parse-string
        run: cd reverse && luajit test-parse-string.lua
      - run: echo "ğŸ This job's status is ${{ job.status }}."
