name: Run JS Tests
on: [push]
jobs:
  Run-JS-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Run tests
        run: |
          cd js/tests
          npm i xxhash@^0.3.0
          node test-text-format.js
          node test-nibs-encoder.js
          node test-nibs-decoder.js
          node test-nibs-utils.js
          node test-cycles.js
          node test-lazy-map.js
          node test-xxhash.js
      - run: echo "ğŸ This job's status is ${{ job.status }}."
